import rpa as r
import time
from time import sleep
import requests
import pandas as pd
import csv

#open your browser and login to thunderquote
print("logging in")
r.init(visual_automation=True)
r.url('https://app.thunderquote.com')
time.sleep(2)
print("go to lead page")
r.click('Find Leads')
time.sleep(3)

#navigate to your desired category
print("navigate to your favourite category")
r.click('/html/body/div[3]/div/div[2]/div/div/div/nav/div/button') #reset
r.click('/html/body/div[3]/div/div[2]/div/div/div/nav/div/ul/li[1]/a') #click on category
r.click(f'(/html/body/div[3]/div/div[2]/div/div/div/nav/div/ul/li[1]/div/a)[1]') #uncheck favourite/current category
r.click('/html/body/div[3]/div/div[2]/div/div/div/nav/div/ul/li[1]/a') #click on category

#access intended category, refer to the list generated by t_setup.py to get the corresponding number for your desired category and input within the square brackets at the end of the line below
r.read(f'(/html/body/div[3]/div/div[2]/div/div/div/nav/div/ul/li[1]/div/a)[88]') 
print(r.read(f'(/html/body/div[3]/div/div[2]/div/div/div/nav/div/ul/li[1]/div/a)[88]')) #verify the category

r.click(f'(/html/body/div[3]/div/div[2]/div/div/div/nav/div/ul/li[1]/div/a)[88]') #click
time.sleep(5)

#Get leads
print("get leads")
pagecount = r.count('/html/body/div[3]/div/div[2]/div/div/div/div/div[2]/button')
print(pagecount)
rfq_ref = []
budget = []
timeframe = []
rfq_url = []

for page in range(2, pagecount):
    page = r.read(f'(/html/body/div[3]/div/div[2]/div/div/div/div/div[2]/button)[{page}]')
    print("You are in page " + page)
    leadcount = r.count('/html/body/div[3]/div/div[2]/div/div/div/div/div[1]/div/div/div[1]/div[2]/button')
    print(leadcount)
    for n in range (1,leadcount+1):
	
        r.click(f'(/html/body/div[3]/div/div[2]/div/div/div/div/div[1]/div/div)[{n}]')
        r.click(f'(/html/body/div[3]/div/div[2]/div/div/div/div/div[1]/div/div/div[1]/div[2]/button)[{n}]')
        
        r.click('/html/body/div[7]/div/div/div[2]/div/div[1]/ul/li[1]')
        r.click('General Info')
        
        rfq_ref_line = r.read('/html/body/div[7]/div/div/div[2]/div/div[1]/div/div[1]/div/table/tbody/tr[9]/td/code')
        print(rfq_ref_line)
        rfq_ref.append(rfq_ref_line)

        budget_line = r.read('/html/body/div[7]/div/div/div[2]/div/div/div/div[1]/div/table/tbody/tr[2]/td')
        print(budget_line)
        budget.append(budget_line)

        timeframe_line = r.read('/html/body/div[7]/div/div/div[2]/div/div/div/div[1]/div/table/tbody/tr[3]/td/text()')
        print(timeframe_line)
        timeframe.append(timeframe_line)

        rfq_url_line = r.read('/html/body/div[7]/div/div/div[2]/div/div[1]/div/div[1]/div/table/tbody/tr[9]/td/small/a/@href')
        print(rfq_url_line)
        rfq_url.append(rfq_url_line)
	

        r.click('/html/body/div[7]/div/div/div[3]/div/div/button[2]')
    page = int(page) + 2
    if page in range(2, pagecount):
        r.click(f'(/html/body/div[3]/div/div[2]/div/div/div/div/div[2]/button)[{page}]')
        page = r.read(f'(/html/body/div[3]/div/div[2]/div/div/div/div/div[2]/button)[{page}]')
        print("changing to page " + str(page))
        time.sleep(4)
    
print("put to csv")
dict = {'RFQ REF': rfq_ref, 'BUDGET': budget, 'TIMEFRAME': timeframe, 'URL': rfq_url}
df2 = pd.DataFrame(dict)
pd.set_option('display.max_rows',df2.shape[0]+1)
print(df2)
df2.to_csv('thunderquote_leads.csv', index=None, sep=' ', mode='a')

r.close()
